# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1c03373fe5d1ba52367c2f439cd9b77c9c5f1d71199bcadc0031c9922b18837c570fd8bbef77e2327d092327d914153786c3512e2ec0302258aa2767cc5a432

test:
  secret_key_base: bc71bc5e2df12b2edbecfedc33d9a77ada861e491c410378d8cc44f0fefab1d866ee06226de4453b3a2ff2834c47bf48789bedc6ed6506fe43b8ec8ca1e2f710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
